### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by schwabe93** [mtdoughty/android_device_samsung_klimtlte#1]
Hi thanks for sharing it, i build cm now with this source but still no data,

**Comment by mtdoughty** [comment]
Hi,

Unfortunately I can't claim to know very much to help you.   I wanted a
recent build for my tablet and had offline copies from before the orginals
got deleted.

I was just pleased I was able to build it!

The issue I had was that no videos would play back, but I thought data was
working ok.

What exact model do you have?
When you say it isn't working do you mean you can't connect to mobile
network at all or or is it just data?

Do you also have the video playback issue?

Many thanks

**Comment by schwabe93** [comment]
Hi Video issue not tested , but on my blisspop Rom and deadmeans LuquidSmooth build no problems. Data not working, my sim was recognized with the right carrier i have, that was the first time since i build for blisspop. Telephony not tested , im on stock Rom now. Have you tested it?

**Comment by mtdoughty** [comment]
Hi,

Sorry for the delay.   Only just had the opportunity to test again.   I can
confirm that data is indeed working for me.

Maybe worth having another go and playing with APN settings if you are
getting as far as seeing the carrier?

Cheers

**Comment by schwabe93** [comment]
OK so are you comming from stock KitKat or Lolipop? People on xda says when they are coming from KitKat Data works but when the com from Lolipop not. By me coming also in statusbar that i have no sim instert is that also by yours?
But i will test with apn settings

**Comment by mtdoughty** [comment]
I've never installed stock lollipop.

I did see no sim inserted when I was in flight mode, but it went away as
soon as I disabled flight mode.

Have you tried swapping out the ril blobs with those in stock lolipop?

**Comment by mtdoughty** [comment]
Hi,

I tried flashing the lollipop radio today and had the same issue s you (sim
not recognised).   It all worked fine though when I swapped out the libs
from a stock Lollipop rom.

I've posted the a build on XDA.   You just need to flash the second zip
file on top to get the data working.

http://forum.xda-developers.com/galaxy-tab-s/development/rom-cyanogenmod-cm-12-1-sm-t705-16gb-t3185121
