### ISSUE TITLE
about the mic issue

### ISSUE THREAD

**Issue by divinites** [mtdoughty/android_device_samsung_klimtlte#2]
any idea about the internal MIC?  I also had the source code downloaded but failed to figure out the reason.

**Comment by mtdoughty** [comment]
I managed to do a bit of investigation this weekend and got it working in
the sense that the microphone picked up audio.  I haven't really had a
chance to test it properly so I'm not sure how well it works.

Essentially all I did was copy the details in the profile when the speaker
phone was in use " voice-speaker-mic-wb" (which worked already) to the
profile used for normal calls "voice-earpiece-mic-wb".

The existing config makes it look like there separate microphones used for
each mode normally so I don't know what impact there is on using one for
both.   Hopefully it will be as simple as tweaking the levels a bit.

If you have time it would be great if you could give it a go?

All you would need to do is copy the attached file in to your /system/etc/
folder (overwriting the existing file) and reboot.   Then make a few calls
to see how it sounds.

You might find you need adjust the microphone a bit.   Try playing with the
values at the under the "voice-earpiece-mic-wb"  path towards the bottom of
the file (under capture paths)

Let me know how you get on.

**Comment by divinites** [comment]
it works!  I suggest that you put this solution on XDA and incorporate the mixer_paths.xml in next release.
